1.0.0/dev
CommunityHiQ/Frends.Community.SecurityThreatDiagnostics pull request #2
Opened 2020-09-23 11:35 UTC by ileinone

Please review security threat diagnostics

2020-09-24 07:59 UTC, EkiH reviewed
Why are build DLLs and .DS_Store files included

2020-09-25 06:03 UTC, EkiH requested changes

2020-09-25 06:03 UTC, EkiH commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.csproj
> +    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
I had t o remove this package to get the tests run in my Visual Studio

2020-09-29 09:36 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.csproj
> +    <PackageReference Include="Owin" Version="1.0.0" />
Fixed

2020-09-29 09:56 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Definition.cs
> +        [DefaultValue("Whitelisted IP addresses to bypass validation")]
Fixed in "Documentation refactoring"

2020-09-29 09:57 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.6.1" />
Fixed in "Removed unnecessary import"

2020-09-29 12:18 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +        CancellationToken cancellationToken = new CancellationToken();
Fixed in "Refactoring of the cancellation token"

2020-09-29 12:18 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.csproj
> +    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0">
Fixed

2020-09-29 12:19 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +            Assert.Throws<ApplicationException>(
It is the same design for all of the tasks, if validation error is raised during the diagnostics an exception will be thrown.

2020-09-29 12:22 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +            options.Encoding = "UTF-8";
Yes, at this point. So we now what kind of character sets are involved.

2020-10-01 08:50 UTC, EkiH requested changes

2020-10-01 08:50 UTC, EkiH commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +            options.Encoding = "UTF-8";
It's specified as a field, it should be named _options. Also you should use a Setup method to initialize it, otherwise it's carried over from test to test. Example:
`
        [SetUp]
        public void SetUp()
        {
           _options = new Option();
           _options.Encoding = "UTF-8"; // Now it has a nice default and you don't have to specify it separately in each test, only overwrite it if necessary
           _validation = new Validation();
           _cancellationToken = CancellationToken.None;
        }
`

2020-10-01 08:50 UTC, EkiH commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +        [Ignore("Ignore a test")]
Why is this ignored?

2020-10-01 08:50 UTC, EkiH commented on Frends.Community.SecurityThreatDiagnostics/Definition.cs
> +        public Dictionary<string, string> HttpHeaders { get; set; }
The HttpHeaders parameter probably should be something that can be easily provided in the Process editor and converted internally to Dictionary<string,string> in the Task

2020-10-16 10:52 UTC, EkiH commented
There are still binary build files left in the version control:
Frends.Community.SecurityThreatDiagnostics.Tests/bin/*

2020-10-16 12:01 UTC, EkiH requested changes

2020-12-10 19:03 UTC, EkiH requested changes

2020-12-10 19:03 UTC, EkiH commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.cs
> +                ChallengeAgainstSecurityThreats(validation, options, cancellationToken);
Isn't this supposed to just validate the encoding, not the actual contents? Otherwise this seems overlapping with the other Task methods

2021-02-11 08:58 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics.Tests/Frends.Community.SecurityThreatDiagnostics.Tests.cs
> +        public void GivenValidTextWhenChallengingValidationThenSecurityThreatDiagnosticsMustReturnIsValidStatus()
Fixed.

2021-02-11 09:15 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.cs
> +                ChallengeAgainstSecurityThreats(validation, options, cancellationToken);
Client software may send information which is under specific encoding, integrations are in it's own encoding and the target system may be in another encoding. Encoding needs to be harmonised.

2021-02-11 09:52 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.cs
> +        private static string Decode(string payload, Options options)
Won't fix (internal static operation).

2021-02-11 12:47 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.cs
> +                            if (rule.Value.Rule.IsMatch(HttpHeaderPair.Value) || base64DecodedHeaderValue.Length > 0 &&
Fixed.

2021-02-11 12:48 UTC, ileinone commented on Frends.Community.SecurityThreatDiagnostics/Frends.Community.SecurityThreatDiagnostics.cs
> +                    ApplicationException applicationException = new ApplicationException(argumentExceptions.ToString());
Gathers hierarchical fine grained exception information.

2021-04-07 12:27 UTC, closed without merging

2021-04-07 12:27 UTC, ileinone commented
Fixed issues.